import type { Partner } from "./types";

export const awsPartner: Partner = {
  slug: "aws",
  name: "AWS",
  category: "Cloud Infrastructure",
  description: "Scalable cloud foundations for secure, high-performing digital products.",
  overviewTitle: "Cloud infrastructure designed around your business",
  overview:
    "We use the AWS ecosystem to plan, deploy, and improve dependable cloud environments. Every architecture is shaped around real product needs, operational clarity, and room for sustainable growth.",
  highlights: ["Cloud architecture", "Scalable deployment", "Performance monitoring"],
  capabilities: [
    { title: "Cloud Architecture", description: "Purpose-built environments aligned with product, security, and performance requirements." },
    { title: "Deployment Systems", description: "Repeatable delivery workflows that help teams release confidently and consistently." },
    { title: "Monitoring & Reliability", description: "Clear operational visibility that supports stable services and faster issue resolution." },
  ],
  metrics: [
    { value: "Secure", label: "Infrastructure by design" },
    { value: "Elastic", label: "Capacity that scales" },
    { value: "Visible", label: "Operational performance" },
  ],
  processTitle: "A clear path from architecture to operation",
  processDescription: "We connect technical decisions to business outcomes throughout the cloud lifecycle.",
  process: ["Assess the product and workload", "Design the cloud foundation", "Deploy and validate", "Monitor, optimize, and scale"],
  assets: {
    logo: "/assets/partners/aws-logo.svg",
    cardIcon: "/assets/partners/aws-logo.svg",
    cardPreviewImages: ["/assets/partners/aws-dashboard.svg", "/assets/partners/aws-cloud.svg"],
    cardArtwork: "infrastructure-grid",
    mediaTreatment: "color",
    heroImages: ["/assets/partners/aws-dashboard.svg", "/assets/partners/aws-cloud.svg"],
    featureAnimation: "/assets/partners/aws-security.svg",
    ctaImage: "/assets/partners/aws-cloud.svg",
  },
  page: {
    displayName: "AWS",
    heroTitle: "Cloud foundations built to perform",
    heroDescription: "Secure, scalable AWS infrastructure designed around real products, reliable operations, and sustainable growth.",
    storeLinks: [],
    websiteUrl: "https://aws.amazon.com/",
    aboutLabel: "About AWS Partnership",
    aboutTitle: "Cloud infrastructure shaped around business needs",
    aboutParagraphs: [
      "Resolute Digitals uses the AWS ecosystem to design dependable cloud environments for modern digital products. Each solution connects infrastructure decisions with security, performance, and operational clarity.",
      "From early architecture through deployment and optimization, the partnership gives teams a foundation that can evolve as products and workloads grow.",
    ],
    values: [
      { title: "Secure by design", description: "Security is considered throughout architecture, deployment, access, and monitoring.", icon: "secure", image: "/assets/partners/aws-security.svg" },
      { title: "Ready to scale", description: "Elastic cloud foundations adapt as users, data, and business requirements change.", icon: "scale", image: "/assets/partners/aws-cloud.svg" },
      { title: "Operationally clear", description: "Monitoring and repeatable delivery systems keep services visible and dependable.", icon: "ease", image: "/assets/partners/aws-dashboard.svg" },
    ],
    featuresTitle: "A complete foundation for dependable cloud products",
    featuresDescription: "Architecture, delivery, security, and monitoring work together as one practical AWS cloud system.",
    featuresLabel: "Cloud Capabilities",
    featureVisualEyebrow: "Secure by design",
    featureVisualTitle: "Protection built into every layer",
    features: [
      { title: "Cloud Architecture", description: "Purpose-built environments aligned with product and workload requirements.", icon: "cloud" },
      { title: "Security Controls", description: "Clear access, network, and data safeguards built into the foundation.", icon: "security" },
      { title: "Scalable Deployment", description: "Repeatable delivery workflows support confident and consistent releases.", icon: "performance" },
      { title: "Performance Monitoring", description: "Useful operational visibility helps teams identify and resolve issues faster.", icon: "performance" },
      { title: "Resilient Systems", description: "Architecture decisions support availability, recovery, and service continuity.", icon: "cloud" },
      { title: "Continuous Optimization", description: "Infrastructure is reviewed and improved as product needs evolve.", icon: "security" },
    ],
    affiliationTitle: "A cloud partnership focused on reliable delivery",
    affiliationDescription: "Resolute Digitals brings AWS capabilities into product delivery through considered architecture and hands-on implementation. The collaboration connects cloud technology with practical business outcomes.",
    paymentStatement: "Resolute Digitals plans and delivers AWS cloud solutions around each client's product, security, and operational requirements. Our role connects technical architecture with dependable implementation.",
    partnershipStatement: "Resolute Digitals works with AWS cloud services as a technology partner, helping clients design, deploy, monitor, and improve scalable infrastructure.",
    companyName: "Resolute Digitals",
    paymentCountry: "AWS Cloud",
    paymentMethods: ["Architecture", "Deployment", "Optimization"],
    partnershipLabel: "Cloud Partnership & Delivery",
    companyEyebrow: "Delivery partner",
    processEyebrow: "Cloud delivery",
    processTitle: "A clear path to production",
    responsibilityLine: "Responsible architecture and implementation",
    partnershipSteps: [
      { title: "Assess", description: "Understand the product, workload, and operational requirements." },
      { title: "Deploy", description: "Build and validate a secure AWS cloud foundation." },
      { title: "Optimize", description: "Monitor performance and improve the environment over time." },
    ],
    galleryTitle: "A closer look at the cloud system",
    galleryDescription: "Explore the architecture, operations, and security layers that support dependable AWS products.",
    galleryLabel: "Cloud Showcase",
    screens: [
      { title: "Cloud Overview", subtitle: "A connected view of the foundation", variant: "home", image: "/assets/partners/aws-cloud.svg" },
      { title: "Operations Dashboard", subtitle: "Performance and delivery at a glance", variant: "prayer", image: "/assets/partners/aws-dashboard.svg" },
      { title: "Security Layer", subtitle: "Protection built into the architecture", variant: "quran", image: "/assets/partners/aws-security.svg" },
    ],
    ctaTitle: "Build a stronger cloud foundation",
    ctaDescription: "Explore AWS or speak with Resolute Digitals about secure, scalable infrastructure for your next product.",
    ctaLinkLabel: "Visit AWS",
  },
  theme: {
    pageBackground: "#FFFFFF",
    pageText: "#080808",
    mutedText: "#5E626A",
    surfaceBackground: "#151515",
    surfaceText: "#FFFFFF",
    surfaceMuted: "#B6B6B6",
    contentAccent: "#FF9900",
    accent: "#FF9900",
    accentDark: "#B96900",
    accentSoft: "rgba(255,153,0,.16)",
    heroBackground: "radial-gradient(circle at 78% 20%, #3A2A13 0%, #151515 42%, #050505 100%)",
    cardBackground: "radial-gradient(circle at 78% 20%, #3A2A13 0%, #151515 42%, #050505 100%)",
    heroText: "#FFFFFF",
    heroMuted: "#B6B6B6",
    sectionBackground: "linear-gradient(135deg, #17130D 0%, #090909 100%)",
    sectionIsLight: false,
    ctaOverlay: "linear-gradient(90deg, rgba(0,0,0,.94) 0%, rgba(0,0,0,.78) 55%, rgba(0,0,0,.25) 100%)",
    navVariant: "default",
    footerVariant: "default",
    logoBackground: "rgba(0,0,0,.72)",
    buttonText: "#ffffff",
  },
};
