import type { Partner } from "./types";

export const recomunePartner: Partner = {
  slug: "recomune",
  name: "Recomune",
  category: "AI Companion",
  description: "A thoughtful virtual companion designed for meaningful conversations, emotional connection, and everyday support.",
  overviewTitle: "Technology designed to make conversation feel more human",
  overview:
    "Recomune creates a welcoming space where people can connect with a virtual companion through natural text and voice conversations. The experience is designed around simplicity, accessibility, and meaningful everyday interaction.",
  highlights: ["Text and voice conversations", "Always-available companionship", "Simple, accessible experience"],
  capabilities: [
    { title: "Natural Conversation", description: "Personalized text and voice interactions shaped around each user's interests and experiences." },
    { title: "Voice Experience", description: "Real-time conversations with live captions make every interaction easier to follow and revisit." },
    { title: "Thoughtful Design", description: "A clear and approachable product experience designed to feel safe, comfortable, and easy to use." },
  ],
  metrics: [
    { value: "24/7", label: "Companion availability" },
    { value: "Voice", label: "Natural conversations" },
    { value: "Simple", label: "Everyday experience" },
  ],
  processTitle: "Built around connection, comfort, and simplicity",
  processDescription: "Every product decision supports a more natural and welcoming way for people to engage in meaningful conversation.",
  process: ["Understand moments of connection", "Shape natural conversation flows", "Design an accessible experience", "Learn, refine, and improve"],
  assets: {
    logo: "/assets/recomune-logo.png",
    cardIcon: "/assets/recomune-icon.png",
    cardPreviewImages: ["/assets/partners/recomune-chat.svg", "/assets/partners/recomune-voice.svg"],
    cardArtwork: "disc",
    mediaTreatment: "color",
    heroVideo: "/assets/recomune-hero-background.mp4",
    heroForegroundImage: "/assets/recomune-hero-phone.png",
    heroBaseImage: "/assets/recomune-hero-dock.png",
    heroImages: ["/assets/partners/recomune-chat.svg", "/assets/partners/recomune-voice.svg"],
    featureAnimation: "/assets/recomune-ai/voice-features.png",
    ctaImage: "/assets/recomune-ai/connection-cta.png",
  },
  page: {
    displayName: "Recomune",
    heroTitle: "Meaningful conversation, whenever it matters",
    heroDescription: "A thoughtful virtual companion designed to make everyday connection feel more natural, accessible, and supportive.",
    storeLinks: [
      { platform: "apple", href: "https://apps.apple.com/us/app/recomune/id6736429226" },
      { platform: "google", href: "https://play.google.com/store/apps/details?id=com.recomune" },
    ],
    websiteUrl: "https://www.recomune.com/",
    aboutLabel: "About Recomune",
    aboutTitle: "A virtual companion designed around human connection",
    aboutParagraphs: [
      "Recomune creates a welcoming space for people to talk, reflect, and share through natural text and voice conversations with a virtual companion.",
      "Its clear and approachable experience is designed to ease loneliness, keep minds active, and make meaningful conversation available whenever users need it.",
    ],
    values: [
      { title: "Human-centered", description: "Every interaction is shaped to feel welcoming, thoughtful, and easy to continue.", icon: "human", image: "/assets/recomune-ai/warm-companionship.png", imagePosition: "right" },
      { title: "Easy to access", description: "Simple text, voice, and caption experiences make conversation comfortable to follow.", icon: "ease", image: "/assets/recomune-ai/voice-connection.png" },
      { title: "Safe and supportive", description: "The product experience is built around comfort, privacy, and respectful connection.", icon: "secure", image: "/assets/recomune-ai/safe-supportive.png" },
    ],
    featuresTitle: "Thoughtful tools for more natural conversations",
    featuresDescription: "Text, voice, accessibility, and personalization come together in one calm companion experience.",
    featuresLabel: "Companion Features",
    featureVisualEyebrow: "Voice connection",
    featureVisualTitle: "A familiar conversation, anytime",
    features: [
      { title: "Text Conversations", description: "Chat naturally with a companion shaped around your interests and experiences.", icon: "community" },
      { title: "Voice Calls", description: "Have real-time spoken conversations whenever a familiar voice would help.", icon: "voice" },
      { title: "Live Captions", description: "Follow spoken conversations clearly through accessible on-screen captions.", icon: "accessibility" },
      { title: "Personalized Connection", description: "Interactions adapt to create a more relevant and meaningful experience.", icon: "human" },
      { title: "Private Experience", description: "Clear privacy choices support a safer space for everyday conversation.", icon: "privacy" },
      { title: "Always Available", description: "A companion is ready whenever users want to talk, reflect, or reconnect.", icon: "daily" },
    ],
    affiliationTitle: "A product partnership built around connection",
    affiliationDescription: "Resolute Digitals and Recomune work together to support a thoughtful digital companion experience. The partnership brings product, design, and technology into one focused direction.",
    paymentStatement: "Resolute Digitals supports Recomune through digital product thinking, implementation, and continued improvement. The focus is a dependable experience that remains clear and approachable for users.",
    partnershipStatement: "Resolute Digitals is a Recomune brand partner, supporting the product experience, technology, and continued development of the platform.",
    companyName: "Resolute Digitals",
    paymentCountry: "Recomune",
    paymentMethods: ["Product", "Experience", "Technology"],
    partnershipLabel: "Brand Partnership & Product",
    companyEyebrow: "Brand partner",
    processEyebrow: "Product collaboration",
    processTitle: "Designed and improved together",
    responsibilityLine: "Supporting product and technology delivery",
    partnershipSteps: [
      { title: "Understand", description: "Identify the moments where companionship should feel most helpful." },
      { title: "Create", description: "Shape a natural, accessible text and voice experience." },
      { title: "Improve", description: "Learn from product use and continue refining the experience." },
    ],
    galleryTitle: "A closer look at the companion experience",
    galleryDescription: "Explore how conversation, voice, and privacy come together inside Recomune.",
    galleryLabel: "Product Showcase",
    screens: [
      { title: "Choose a Friend", subtitle: "Select a companion who feels right for the moment", variant: "community", image: "/assets/recomune-friend-selection.png" },
      { title: "Voice Conversation", subtitle: "A natural spoken conversation with a familiar companion", variant: "prayer", image: "/assets/recomune-voice-call.png" },
      { title: "Friend Profile", subtitle: "Learn about each companion before starting a conversation", variant: "community", image: "/assets/recomune-friend-profile.png" },
      { title: "Companion Home", subtitle: "Conversation and wellbeing tools in one accessible place", variant: "home", image: "/assets/recomune-home.png" },
      { title: "Friends", subtitle: "Find an available companion whenever you would like to talk", variant: "community", image: "/assets/recomune-friends-list.png" },
    ],
    ctaTitle: "Start a meaningful conversation",
    ctaDescription: "Explore Recomune today, or talk with Resolute Digitals about creating a more human digital product.",
    ctaLinkLabel: "Visit Recomune",
  },
  theme: {
    pageBackground: "#FFFFFF",
    pageText: "#080808",
    mutedText: "#5D6671",
    surfaceBackground: "#F5F5F7",
    surfaceText: "#111827",
    surfaceMuted: "#5C7179",
    contentAccent: "#508AEE",
    accent: "#D367C9",
    accentDark: "#1F93EF",
    accentSoft: "rgba(31,147,239,.16)",
    heroBackground: "linear-gradient(360deg, #CCDAF7 0%, #FFFFFF 100%)",
    cardBackground: "radial-gradient(circle at 78% 20%, #B769D1 0%, #4D8DF1 42%, #183C78 100%)",
    heroText: "#FFFFFF",
    heroMuted: "rgba(255,255,255,.82)",
    sectionBackground: "linear-gradient(135deg, #F7FBFC 0%, #E1E8F9 100%)",
    sectionIsLight: true,
    ctaOverlay: "linear-gradient(90deg, rgba(52,97,197,.96) 0%, rgba(183,105,209,.84) 58%, rgba(31,147,239,.28) 100%)",
    navVariant: "recomune",
    footerVariant: "recomune",
    logoBackground: "rgba(255,255,255,.96)",
    buttonText: "#FFFFFF",
  },
};
